import = [
  #"~/.config/alacritty/themes/themes/github_dark.toml",
  "/Users/antoine/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin_macchiato.toml" 
  ]
# [env]
# TERM = "xterm-256color"
#
[shell]
program = "/bin/bash"
args = ["-l"]

[window]
decorations = "buttonless"
padding = { x = 5, y = 3 }
startup_mode = "maximized"

[font]
size = 15 

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
