#!/bin/bash

# This a the setup script for my config. The idea is to be able to run this after cloning my dotfiles repo on a Mac or Linux system
# and be up and running very quickly
#
# This script should be ran as sudo

export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"/bash
mkdir -p "$XDG_CONFIG_HOME"/alacritty
mkdir -p "$XDG_CONFIG_HOME"/alacritty/themes/themes

# Curl alacritty cappuccin-macchiato theme
curl -LO --output-dir "$XDG_CONFIG_HOME"/alacritty/themes/themes https://github.com/catppuccin/alacritty/raw/main/catppuccin-macchiato.toml

# Install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install alacritty
/opt/homebrew/bin/brew install --cask alacritty

# Install nerd font jetbrains
/opt/homebrew/bin/brew tap homebrew/cask-fonts
/opt/homebrew/bin/brew install --cask font-jetbrains-mono-nerd-font 

# Install nvim and AstroNvim
/opt/homebrew/bin/brew install neovim
git clone https://github.com/antoinelhermitte/nvim ~/.config/nvim

# Install other Mac Packages
/opt/homebrew/bin/brew install --cask obsidian vlc firefox amethyst hiddenbar karabiner-elements bitwarden signal
/opt/homebrew/bin/brew install tmux ripgrep lazygit bottom wireguard-go ffmpeg gh starship fzf MonitorControl pyright

mkdir -p "$XDG_CONFIG_HOME"/karabiner/complex_modifications

# Change default shell to bash
chsh -s /bin/bash

# Import config files
ln -sf "$PWD/alacritty.toml" "$HOME"/.alacritty.toml
ln -sf "$PWD/bash_profile" "$HOME"/.bash_profile
ln -sf "$PWD/bashrc" "$HOME"/.bashrc
ln -sf "$PWD/tmux.conf" "$HOME"/.tmux.conf
ln -sf "$PWD/custom-capslock.json" "$XDG_CONFIG_HOME"/karabiner/complex_modifications/custom-capslock.json
ln -sf "$PWD/karabiner.json" "$XDG_CONFIG_HOME"/karabiner/karabiner.json
ln -sf "$PWD/starship.toml" "$XDG_CONFIG_HOME"/starship.toml

# Install firefox addons (bitwarden, ublock, vimium, pocket)

# Clean installation packages
#rm -rf tmp
