#!/bin/bash

rsync -av ~/.bashrc bashrc
rsync -av ~/.bash_profile bash_profile
rsync -av ~/.bashrc bashrc
rsync -av ~/.alacritty.toml alacritty.toml
rsync -av ~/.config/nvim/lua/user/init.lua init.lua 
rsync -av ~/.config/karabiner/assets/complex_modifications/custom-capslock.json custom-capslock.json
rsync -av ~/.config/nvim/lua/user/init.lua init.lua 
rsync -av ~/.config/karabiner/karabiner.json karabiner.json
